project:
  type: website
  output-dir: _site
  resources:
    - Logos/
    - styles.css

website:
  title: "Banff National Park - NABat Trend Results 2020-2025"
  site-url: https://github.com/bp-sensr/NABat-BNP-2025/